### ISSUE TITLE
Suggestion: define `elfeed-score-load`

### ISSUE THREAD

**Issue by firmart** [sp1ff/elfeed-score#8]
The function `elfeed-score-enable` installs (or not) the sort function and load the score file. It would be nice to separate the snippet which loads the score file to a separate function so that loading and unloading functions are both available. When I modified my score file, I used `elfeed-score-enable` to load it, but the denomination sounds unnatural.

**Comment by sp1ff** [comment]
Do you mean like `elfeed-score-load-score-file` (bound to `l` in the keymap)? :grin:

**Comment by firmart** [comment]
Ah, yeah, my bad... IMO, it would be nice to reduce a bit of user
interaction: i.e. let write/load functions don't prompt by default so
that advanced users using multiple score files could do something like
`C-u = l`.

There is a slight inconvenient thing when I add new rules in the score
file. I have to immediately load the score file, otherwise if I do
rescore some entries with `= s`, it would overwrite silently my score
file. So may it may be worthwhile to use a file watcher to monitor the
score file and auto-reload it when is changed. Or, alternatively, load
again the score file before write it.

P.S. Thanks again for this wonderful package! I used to have my own
scoring mechanism, but your package simplify greatly the task.

**Comment by sp1ff** [comment]
I'd be uncomfortable just re-loading the thing unconditionally, but maybe check if the file is newer than the last read before scoring & warn? But in that case, it could be challenging to "merge" any in-memory changes with those that occurred on-disk. Hmmmm.... Oh! We write to disk after every scoring run, so it wouldn't be that bad. So yeah, maybe warn on score file changes since the last sync before scoring again?

>  Thanks again for this wonderful package!

You are most welcome; just glad someone's getting some use out of it. Thank you for all the bug reports & suggestions!

**Comment by firmart** [comment]
> maybe warn on score file changes since the last sync before scoring again?

Sounds good to me.

**Comment by sp1ff** [comment]
I'm going to close this in favor of issue #13, which I think captures the problem more succinctly -- tagged you there @firmart
